# Arificial Newral Network

## Importing library

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Importing DataSet

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = df.iloc[:, 3:-1]

In [6]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [7]:
y = df['Exited']

In [8]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

## Encoding Catagorical Data

In [9]:
X.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

## Searching for the type object which has 2 categories

In [10]:
less_than_2 = []
for col in X.columns:
    if len(X[col].unique()) == 2 and X[col].dtype=='object':
        less_than_2.append(col)

In [11]:
less_than_2

['Gender']

## Applying Label Encoding

In [12]:
X[less_than_2[0]] = X[less_than_2[0]].apply(lambda x:1 if x=='Female' else 0)

In [13]:
X.dtypes

CreditScore          int64
Geography           object
Gender               int64
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [14]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       1   42       2       0.00              1   
1          608     Spain       1   41       1   83807.86              1   
2          502    France       1   42       8  159660.80              3   
3          699    France       1   39       1       0.00              2   
4          850     Spain       1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

## OneHot-encoding for a data more than 2 catagories


In [15]:
X = pd.get_dummies(X)

In [16]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       1   42       2       0.00              1          1   
1             608       1   41       1   83807.86              1          0   
2             502       1   42       8  159660.80              3          1   
3             699       1   39       1       0.00              2          0   
4             850       1   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       0   39       5       0.00              2          1   
9996          516       0   35      10   57369.61              1          1   
9997          709       1   36       7       0.00              1          0   
9998          772       0   42       3   75075.31              2          1   
9999          792       1   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0                  1        101348.88                 1                  0   
1                  1        112542.58                 0                  0   
2                  0        113931.57                 1                  0   
3                  0         93826.63                 1                  0   
4                  1         79084.10                 0                  0   
...              ...              ...               ...                ...   
9995               0         96270.64                 1                  0   
9996               1        101699.77                 1                  0   
9997               1         42085.58                 1                  0   
9998               0         92888.52                 0                  1   
9999               0         38190.78                 1                  0   

      Geography_Spain  
0                   0  
1                   1  
2                   0  
3                   0  
4                   1  
...               ...  
9995                0  
9996                0  
9997                0  
9998                0  
9999                0  

[10000 rows x 12 columns]

In [17]:
X.dtypes

CreditScore            int64
Gender                 int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_France       uint8
Geography_Germany      uint8
Geography_Spain        uint8
dtype: object

## converting back to Arrays

In [18]:
X = X.values

In [19]:
X

array([[619.,   1.,  42., ...,   1.,   0.,   0.],
       [608.,   1.,  41., ...,   0.,   0.,   1.],
       [502.,   1.,  42., ...,   1.,   0.,   0.],
       ...,
       [709.,   1.,  36., ...,   1.,   0.,   0.],
       [772.,   0.,  42., ...,   0.,   1.,   0.],
       [792.,   1.,  28., ...,   1.,   0.,   0.]])

In [20]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [21]:
y = y.values

In [22]:
y

array([1, 0, 1, ..., 1, 1, 0])

## Splitting the data into training and testing

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [24]:
X_test

array([[597.,   1.,  35., ...,   0.,   1.,   0.],
       [523.,   1.,  40., ...,   1.,   0.,   0.],
       [706.,   1.,  42., ...,   0.,   0.,   1.],
       ...,
       [578.,   0.,  36., ...,   0.,   0.,   1.],
       [650.,   0.,  34., ...,   0.,   1.,   0.],
       [573.,   0.,  30., ...,   0.,   1.,   0.]])

## Feuture Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [26]:
X_test

array([[-0.55204276,  1.09168714, -0.36890377, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-1.31490297,  1.09168714,  0.10961719, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       [ 0.57162971,  1.09168714,  0.30102557, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227, -0.91601335, -0.27319958, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-0.00566991, -0.91601335, -0.46460796, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-0.79945688, -0.91601335, -0.84742473, ..., -1.01460667,
         1.75486502, -0.57369368]])

## Building ANN 

In [27]:
ann = tf.keras.models.Sequential()

In [28]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [29]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

In [30]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [31]:
ann.add(tf.keras.layers.Dense(units=3, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training ANN

In [33]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics= ['accuracy'])

In [39]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 500)

Epoch 1/500
250/250 [==============================] - 0s 583us/step - loss: 0.3271 - accuracy: 0.8694
Epoch 2/500
250/250 [==============================] - 0s 567us/step - loss: 0.3274 - accuracy: 0.8677
Epoch 3/500
250/250 [==============================] - 0s 563us/step - loss: 0.3270 - accuracy: 0.8684
Epoch 4/500
250/250 [==============================] - 0s 575us/step - loss: 0.3269 - accuracy: 0.8687
Epoch 5/500
250/250 [==============================] - 0s 562us/step - loss: 0.3259 - accuracy: 0.8683
Epoch 6/500
250/250 [==============================] - 0s 548us/step - loss: 0.3269 - accuracy: 0.8686
Epoch 7/500
250/250 [==============================] - 0s 589us/step - loss: 0.3262 - accuracy: 0.8681
Epoch 8/500
250/250 [==============================] - 0s 610us/step - loss: 0.3252 - accuracy: 0.8676
Epoch 9/500
250/250 [==============================] - 0s 572us/step - loss: 0.3267 - accuracy: 0.8692
Epoch 10/500
250/250 [==============================] - 0s 581us/step - l

250/250 [==============================] - 0s 571us/step - loss: 0.3201 - accuracy: 0.8731
Epoch 80/500
250/250 [==============================] - 0s 556us/step - loss: 0.3202 - accuracy: 0.8726
Epoch 81/500
250/250 [==============================] - 0s 555us/step - loss: 0.3202 - accuracy: 0.8686
Epoch 82/500
250/250 [==============================] - 0s 559us/step - loss: 0.3201 - accuracy: 0.8724
Epoch 83/500
250/250 [==============================] - 0s 563us/step - loss: 0.3204 - accuracy: 0.8733
Epoch 84/500
250/250 [==============================] - 0s 672us/step - loss: 0.3190 - accuracy: 0.8723
Epoch 85/500
250/250 [==============================] - 0s 566us/step - loss: 0.3192 - accuracy: 0.8704
Epoch 86/500
250/250 [==============================] - 0s 675us/step - loss: 0.3209 - accuracy: 0.8729
Epoch 87/500
250/250 [==============================] - 0s 712us/step - loss: 0.3186 - accuracy: 0.8720
Epoch 88/500
250/250 [==============================] - 0s 547us/step - loss:

250/250 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8719
Epoch 158/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8717
Epoch 159/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3174 - accuracy: 0.8716
Epoch 160/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3168 - accuracy: 0.8712
Epoch 161/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8735
Epoch 162/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8735
Epoch 163/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8716
Epoch 164/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8715
Epoch 165/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8727
Epoch 166/500
250/250 [==============================] - 0s 2ms/step - loss: 0.3165 - a

250/250 [==============================] - 0s 741us/step - loss: 0.3158 - accuracy: 0.8740
Epoch 236/500
250/250 [==============================] - 0s 799us/step - loss: 0.3164 - accuracy: 0.8731
Epoch 237/500
250/250 [==============================] - 0s 755us/step - loss: 0.3169 - accuracy: 0.8731
Epoch 238/500
250/250 [==============================] - 0s 782us/step - loss: 0.3164 - accuracy: 0.8717
Epoch 239/500
250/250 [==============================] - 0s 746us/step - loss: 0.3165 - accuracy: 0.8726
Epoch 240/500
250/250 [==============================] - 0s 751us/step - loss: 0.3163 - accuracy: 0.8717
Epoch 241/500
250/250 [==============================] - 0s 1ms/step - loss: 0.3159 - accuracy: 0.8742
Epoch 242/500
250/250 [==============================] - 0s 867us/step - loss: 0.3149 - accuracy: 0.8733
Epoch 243/500
250/250 [==============================] - 0s 824us/step - loss: 0.3159 - accuracy: 0.8725
Epoch 244/500
250/250 [==============================] - 0s 844us/step 

250/250 [==============================] - 0s 853us/step - loss: 0.3153 - accuracy: 0.8737
Epoch 314/500
250/250 [==============================] - 0s 767us/step - loss: 0.3151 - accuracy: 0.8729
Epoch 315/500
250/250 [==============================] - 0s 766us/step - loss: 0.3149 - accuracy: 0.8714
Epoch 316/500
250/250 [==============================] - 0s 792us/step - loss: 0.3153 - accuracy: 0.8719
Epoch 317/500
250/250 [==============================] - 0s 866us/step - loss: 0.3154 - accuracy: 0.8724
Epoch 318/500
250/250 [==============================] - 0s 767us/step - loss: 0.3152 - accuracy: 0.8735
Epoch 319/500
250/250 [==============================] - 0s 933us/step - loss: 0.3154 - accuracy: 0.8726
Epoch 320/500
250/250 [==============================] - 0s 772us/step - loss: 0.3150 - accuracy: 0.8736
Epoch 321/500
250/250 [==============================] - 0s 776us/step - loss: 0.3144 - accuracy: 0.8749
Epoch 322/500
250/250 [==============================] - 0s 856us/ste

250/250 [==============================] - 0s 798us/step - loss: 0.3148 - accuracy: 0.8716
Epoch 392/500
250/250 [==============================] - 0s 856us/step - loss: 0.3142 - accuracy: 0.8734
Epoch 393/500
250/250 [==============================] - 0s 785us/step - loss: 0.3147 - accuracy: 0.8721
Epoch 394/500
250/250 [==============================] - 0s 877us/step - loss: 0.3134 - accuracy: 0.8725
Epoch 395/500
250/250 [==============================] - 0s 761us/step - loss: 0.3148 - accuracy: 0.8727
Epoch 396/500
250/250 [==============================] - 0s 776us/step - loss: 0.3138 - accuracy: 0.8733
Epoch 397/500
250/250 [==============================] - 0s 728us/step - loss: 0.3143 - accuracy: 0.8712
Epoch 398/500
250/250 [==============================] - 0s 804us/step - loss: 0.3139 - accuracy: 0.8715
Epoch 399/500
250/250 [==============================] - 0s 803us/step - loss: 0.3141 - accuracy: 0.8726
Epoch 400/500
250/250 [==============================] - 0s 731us/ste

250/250 [==============================] - 0s 739us/step - loss: 0.3138 - accuracy: 0.8723
Epoch 470/500
250/250 [==============================] - 0s 726us/step - loss: 0.3137 - accuracy: 0.8719
Epoch 471/500
250/250 [==============================] - 0s 748us/step - loss: 0.3134 - accuracy: 0.8721
Epoch 472/500
250/250 [==============================] - 0s 774us/step - loss: 0.3117 - accuracy: 0.8723
Epoch 473/500
250/250 [==============================] - 0s 735us/step - loss: 0.3129 - accuracy: 0.8723
Epoch 474/500
250/250 [==============================] - 0s 729us/step - loss: 0.3121 - accuracy: 0.8735
Epoch 475/500
250/250 [==============================] - 0s 749us/step - loss: 0.3130 - accuracy: 0.8733
Epoch 476/500
250/250 [==============================] - 0s 720us/step - loss: 0.3144 - accuracy: 0.8734
Epoch 477/500
250/250 [==============================] - 0s 720us/step - loss: 0.3127 - accuracy: 0.8705
Epoch 478/500
250/250 [==============================] - 0s 787us/ste

## Making Prediction

In [35]:
ann.predict(ss.transform([[600, 0, 40, 3, 60000, 2, 1, 1, 50000, 1,0,0]])) > 0.5

array([[False]])

In [36]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [37]:
X_test

array([[-0.55204276,  1.09168714, -0.36890377, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-1.31490297,  1.09168714,  0.10961719, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       [ 0.57162971,  1.09168714,  0.30102557, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227, -0.91601335, -0.27319958, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-0.00566991, -0.91601335, -0.46460796, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-0.79945688, -0.91601335, -0.84742473, ..., -1.01460667,
         1.75486502, -0.57369368]])

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 203  202]]


0.8625